version: '3.3'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234 # Contraseña del usuario root
      - MYSQL_DATABASE=my_database # Base de datos inicial (opcional)
    ports:
      - '3306:3306' # Mapea el puerto 3306 del contenedor al puerto 3306 de tu máquina local
    volumes:
      - mysql-data:/var/lib/mysql # Volumen persistente para los datos de la base de datos

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=1234
    ports:
      - '8080:80'

volumes:
  mysql-data: # Definir un volumen para los datos persistentes de MySQL
